name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your Python version if necessary

    - name: Install dependencies
      run: |
        pip install sphinx

    - name: Build the Sphinx documentation
      run: |
        cd docs  # Change to your docs directory
        make html  # or whatever build command you use

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git clone --branch=docs https://github.com/${{ github.repository }} ../docs-output
        rm -rf ../docs-output/*
        cp -r build/html/* ../docs-output/
        cd ../docs-output
        git add --all
        git commit -m "Deploy Sphinx documentation [skip ci]"
        git push origin docs

    - name: Clean up
      run: rm -rf ../docs-output
